# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'favor' do
  use_frameworks!

    pod 'RealmSwift'

  target 'favorTests' do
    inherit! :search_paths
  end

end
